services:
  app:
    build: .
    container_name: subgame-api
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.4
    container_name: subgame-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - subgame-mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: subgame-redis
    ports:
      - "6379:6379"

volumes:
  subgame-mysql_data: