package services

import (
	"bnsp2/server/models"
	"bytes"
	"fmt"

	"github.com/jung-kurt/gofpdf"
)

func formatRupiah(num int) string {
	return fmt.Sprintf("Rp %s", formatNumber(num))
}

// helper biar ada titik ribuan
func formatNumber(num int) string {
	s := fmt.Sprintf("%d", num)
	n := len(s)
	if n <= 3 {
		return s
	}

	var result string
	for i, c := range s {
		if (n-i)%3 == 0 && i != 0 {
			result += "."
		}
		result += string(c)
	}
	return result
}

func GenerateInvoiceBuffer(order models.Order, userName string, productTitle string) (*bytes.Buffer, error) {
	var buf bytes.Buffer

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(14, 20, 14)
	pdf.AddPage()

	// ===== HEADER =====
	pdf.SetFont("Arial", "B", 18)
	pdf.Cell(0, 10, "INVOICE")

	pdf.SetFont("Arial", "", 10)

	// posisi kanan atas
	pdf.SetXY(140, 20)
	pdf.Cell(60, 5, "Invoice ID: "+order.Invoice)

	pdf.SetXY(140, 26)
	pdf.Cell(60, 5, "Date: "+order.CreatedAt.Format("02 Jan 2006"))

	pdf.Ln(10)

	// ===== CUSTOMER =====
	pdf.SetFont("Arial", "B", 11)
	pdf.Cell(0, 6, "Bill To:")

	pdf.Ln(6)

	pdf.SetFont("Arial", "", 10)
	pdf.MultiCell(100, 6, userName, "", "L", false)

	pdf.Ln(2)

	// ===== LINE =====
	y := pdf.GetY()
	pdf.Line(14, y, 196, y)

	pdf.Ln(6)

	// ===== TABLE HEADER =====
	pdf.SetFont("Arial", "B", 10)
	pdf.Cell(100, 6, "Product")
	pdf.Cell(30, 6, "Qty")
	pdf.CellFormat(52, 6, "Total", "", 0, "R", false, 0, "")

	pdf.Ln(6)

	y = pdf.GetY()
	pdf.Line(14, y, 196, y)

	pdf.Ln(4)

	// ===== TABLE ROW =====
	pdf.SetFont("Arial", "", 10)

	startY := pdf.GetY()

	// Product (multi line support)
	pdf.MultiCell(100, 6, productTitle, "", "L", false)

	endY := pdf.GetY()

	// set posisi ke kanan untuk qty & total
	pdf.SetXY(114, startY)
	pdf.Cell(30, 6, fmt.Sprintf("%d", order.Qty))

	pdf.SetXY(144, startY)
	pdf.CellFormat(52, 6, formatRupiah(order.Total), "", 0, "R", false, 0, "")

	pdf.Ln(endY - startY + 6)

	// ===== TOTAL BOX =====
	boxY := pdf.GetY() + 10

	pdf.Rect(120, boxY, 76, 20, "")

	pdf.SetXY(122, boxY+6)
	pdf.SetFont("Arial", "", 10)
	pdf.Cell(40, 6, "Total Paid")

	pdf.SetXY(122, boxY+12)
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(70, 6, formatRupiah(order.Total), "", 0, "R", false, 0, "")

	// ===== FOOTER =====
	pdf.SetFont("Arial", "", 9)

	pdf.SetXY(14, 130)
	pdf.Cell(0, 5, "Thank you for your purchase!")

	pdf.SetXY(14, 136)
	pdf.Cell(0, 5, "Generated by SubGame Platform")

	// ===== OUTPUT =====
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}

	return &buf, nil
}
